config {
  type: "table",
  schema: "staging2"
}

select
    * except(num_orders_sales_item_price_credit,
            num_orders_sales_other,
            num_orders_logistics_shipping_fee_paid_by_seller,
            num_orders_logistics_shipping_fee__paid_by_customer,
            num_orders_logistics_shipping_fee_voucher__by_lazada,
            num_orders_logistics_other,
            num_orders_logistics_shipping_fee_subsidy__by_seller,
            num_orders_marketing_fees_promotional_charges_vouchers,
            num_orders_marketing_fees_free_shipping_max_fee,
            num_orders_marketing_fees_lcp_fee,
            num_orders_marketing_fees_promotional_charges_flexi_combo,
            num_orders_marketing_fees_lazcoin_discount,
            num_orders_marketing_fees_other,
            num_orders_lazada_fees_payment_fee,
            num_orders_lazada_fees_commission,
            num_orders_lazada_fees_lazada_bonus,
            num_orders_lazada_fees_lazada_bonus___lzd_co_fund,
            num_orders_lazada_fees_other,
            num_orders_claims_other,
            num_other_services_marketing_fees_sponsored_affiliates,
            num_other_services_marketing_fees_other,
            num_refunds_sales_refund,
            num_refunds_logistics_refund,
            num_refunds_marketing_fees_refund,
            num_refunds_lazada_fees_refund,
            num_refunds_claims_refund),
    num_orders_sales_item_price_credit as orders_sales_item_price_credit,
    num_orders_sales_other as orders_sales_other,
    num_orders_logistics_shipping_fee_paid_by_seller as orders_logistics_shipping_fee_paid_by_seller,
    num_orders_logistics_shipping_fee__paid_by_customer as orders_logistics_shipping_fee__paid_by_customer,
    num_orders_logistics_shipping_fee_voucher__by_lazada as orders_logistics_shipping_fee_voucher__by_lazada,
    num_orders_logistics_other as orders_logistics_other,
    num_orders_logistics_shipping_fee_subsidy__by_seller as orders_logistics_shipping_fee_subsidy__by_seller,
    num_orders_marketing_fees_promotional_charges_vouchers as orders_marketing_fees_promotional_charges_vouchers,
    num_orders_marketing_fees_free_shipping_max_fee as orders_marketing_fees_free_shipping_max_fee,
    num_orders_marketing_fees_lcp_fee as orders_marketing_fees_lcp_fee,
    num_orders_marketing_fees_promotional_charges_flexi_combo as orders_marketing_fees_promotional_charges_flexi_combo,
    num_orders_marketing_fees_lazcoin_discount as orders_marketing_fees_lazcoin_discount,
    num_orders_marketing_fees_other as orders_marketing_fees_other,
    num_orders_lazada_fees_payment_fee as orders_lazada_fees_payment_fee,
    num_orders_lazada_fees_commission as orders_lazada_fees_commission,
    num_orders_lazada_fees_lazada_bonus as orders_lazada_fees_lazada_bonus,
    num_orders_lazada_fees_lazada_bonus___lzd_co_fund as orders_lazada_fees_lazada_bonus___lzd_co_fund,
    num_orders_lazada_fees_other as orders_lazada_fees_other,
    num_orders_claims_other as orders_claims_other,
    num_other_services_marketing_fees_sponsored_affiliates as other_services_marketing_fees_sponsored_affiliates,
    num_other_services_marketing_fees_other as other_services_marketing_fees_other,
    num_refunds_sales_refund as refunds_sales_refund,
    num_refunds_logistics_refund as refunds_logistics_refund,
    num_refunds_marketing_fees_refund as refunds_marketing_fees_refund,
    num_refunds_lazada_fees_refund as refunds_lazada_fees_refund,
    num_refunds_claims_refund as refunds_claims_refund
from
    (
        select * from
        (
            select
                main_brand,
                brand, 
                region,
                currency,
                order_no, 
                orderItem_no,
                seller_sku,
                transaction_dt,
                transaction_fee_name, 
                cast(amount as numeric) as amount
            from
                ${ref("lazada_transactions_union")}

        )

        PIVOT
        (
            -- aggregate
            cast(sum(amount) as numeric) as num, min(transaction_dt) as date
            -- pivot_column
            FOR transaction_fee_name in ${mapping.pivot_col_name()}
        )
    )

  