config {
  type: "table",
  schema: "staging2"
}

select
    a.*,
    JSON_VALUE(fulfillment, '$.id') as fulfillments_id,
    JSON_VALUE(fulfillment, '$.status') as fulfillments_status,
    JSON_VALUE(fulfillment, '$.location_id') as fulfillments_location_id,
    b.location as fulfillments_location,

    JSON_VALUE(fulfillment, '$.tracking_company') as fulfillments_tracking_company,
    JSON_VALUE(fulfillment, '$.tracking_number') as fulfillments_tracking_number,
    JSON_VALUE(fulfillment, '$.tracking_url') as fulfillments_tracking_url,
    JSON_EXTRACT_ARRAY(fulfillment, '$.line_items') as fulfillment_line_items,
    
    datetime(left(JSON_VALUE(fulfillment, '$.created_at'), 19)) as fulfillments_created_at,
    date(left(JSON_VALUE(fulfillment, '$.created_at'), 10)) as fulfillments_created_dt,

    datetime(left(JSON_VALUE(fulfillment, '$.updated_at'), 19)) as fulfillments_updated_at,
    date(left(JSON_VALUE(fulfillment, '$.updated_at'), 10)) as fulfillments_updated_dt
from 
    ${ref("shopify_orders_union")} a, unnest(json_extract_array(fulfillments)) as fulfillment
left join
    (select distinct location_id, location from ${ref("shopify_orders_union")}) b
on JSON_VALUE(fulfillment, '$.location_id') = cast(b.location_id as string)
